from selenium.webdriver.common.by import By
from src.testproject.classes import DriverStepSettings, StepSettings
from src.testproject.decorator import report_assertion_errors
from src.testproject.enums import SleepTimingType
from src.testproject.sdk.drivers import webdriver
import pytest


"""
This pytest test was automatically generated by TestProject
    Project: OttoDigital
    Package: TestProject.Generated.Tests.OttoDigital
    Test: LoginCMS
    Generated by: Tara Eka Putri (tara.putri@ottodigital.id)
    Generated on 06/11/2021, 08:56:51
"""


@pytest.fixture()
def driver():
    driver = webdriver.Chrome(token="wDKIgkEh7rbDv-VUxmzTDQuXRY9IQNMSN6uJTnh6-Xk1",
                              project_name="OttoDigital",
                              job_name="LoginCMS")
    step_settings = StepSettings(timeout=15000,
                                 sleep_time=500,
                                 sleep_timing_type=SleepTimingType.Before)
    with DriverStepSettings(driver, step_settings):
        yield driver
    driver.quit()


@report_assertion_errors
def test_main(driver):
    """Login sebagai Administrator."""
    # Test Parameters
    # Auto generated application URL parameter
    ApplicationURL = "https://dev.pede.id/cms-community/"

    # 1. Navigate to '{ApplicationURL}'
    # Navigates the specified URL (Auto-generated)
    driver.get(f'{ApplicationURL}')

    # 2. Click 'Email'
    email = driver.find_element(By.CSS_SELECTOR,
                                "#email")
    email.click()

    # 3. Type 'webmaster@ottocummunity.com' in 'Email'
    email = driver.find_element(By.CSS_SELECTOR,
                                "#email")
    email.send_keys("webmaster@ottocummunity.com")

    # 4. Click 'Password'
    password = driver.find_element(By.XPATH,
                                   "//input[@placeholder = 'Password']")
    password.click()

    # 5. Type '@!oc202Satu' in 'Password'
    password = driver.find_element(By.XPATH,
                                   "//input[@placeholder = 'Password']")
    password.send_keys("@!oc202Satu")

    # 6. Click 'Login'
    login = driver.find_element(By.XPATH,
                                "//button[. = '\n          Login\n        ']")
    login.click()

    # 7. Does 'Ottocomunity' contain 'Ottocomunity'?
    ottocomunity = driver.find_element(By.XPATH,
                                       "//span[. = 'Ottocomunity']")
    step_output = ottocomunity.text
    assert step_output and ("Ottocomunity" in step_output)
